name: cd-deploy2-2-deploy

on:
  push:
    paths:
      - ".github/workflows/cd-deploy2-2-deploy.yml"
      - "api/**"
  workflow_dispatch: # manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # all commits, so we can generate version off of tags/commit sha...
      - uses: docker/setup-buildx-action@v3
      - run: docker buildx ls
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - run: ./build-push.sh # can reuse local build scripts for CI/CD
        working-directory: api

  deploy:
    needs: build # *** build must complete first (ensure image is pushed)
    runs-on: ubuntu-latest
    environment:
      name: production2
      url: ${{ steps.webapp-deploy.outputs.webapp-url }} # once app deploys, azure action returns a URL (below), we can have that show up in the deployments tab
    steps:
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDS_2 }} # FYI env specific secret to restrict access and require approval
      #     curl  "http://gh-actions-web-api.azurewebsites.net/" => note the current app version
      - id: webapp-deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: gh-actions-web-api
          images: weshigbee/actions-web-test:latest
          resource-group-name: gh-actions
          # FYI
          #    az webapp list --output table
