name: dotnet-build

on:
  push:
    paths:
      - ".github/workflows/dotnet-build.yml"
      - "net6/**"
  workflow_dispatch: # manual

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: net6
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          dotnet-quality: preview
      - run: dotnet --version
      - run: dotnet --list-runtimes
      - run: dotnet --list-sdks
      - run: dotnet build
      - run: ls bin/Debug/net6.0

