name: live-upper-capture

on:
  push:
    paths:
      - ".github/workflows/live-upper-capture.yml"
      - "upper/**"
  workflow_dispatch: # manual

jobs:
  capture:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: upper
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22 # use cached version (when avail) for faster setup
          cache-dependency-path: ./upper/go.sum
      - run: ls
      - run: go build
      - run: ls
      - run: go test -v
      - run: ./upper foo the bar
      - uses: actions/upload-artifact@v4 # reiterate demo of click through for version
          # SHOW actions.yml too => https://github.com/actions/upload-artifact/blob/v4/action.yml
          # for right tag too
        with:
          compression-level: -1
          name: "renamed-${{ github.run_number }}"
          path: ./upper/upper # show entire dir capture
