name: script-thanks

on:
  issues:
    types: opened
  workflow_dispatch: # manual

jobs:
  thanks:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v7
        id: issue_script
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.issue.number || 4;
            console.log(`issue_number: ${issue_number}`);
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            result = await github.rest.issues.get({
              owner,
              repo,
              issue_number
            });
            const comment = await github.rest.issues.createComment({
              repo, owner, issue_number,
              body: "Thanks for your contribution!"
            });
            console.log(comment.data);

# context.issue.number
