name: script-thanks

on:
  issues:
    types: opened
  workflow_dispatch: # manual

jobs:
  thanks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: issue_script
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = 4;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            result = await github.rest.issues.get({
              owner,
              repo,
              issue_number
            });
            console.log(result);

# context.issue.number
