name: upper-xplat-release-experiment

on:
  push:
    paths:
      - ".github/workflows/upper-xplat-release-experiment.yml"
      - "upper/**"
  workflow_dispatch: # manual

defaults:
  run:
    working-directory: upper

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22
          cache-dependency-path: ./upper/go.sum

      - run: ./build.xplat.sh

      - run: echo "${{ toJson(github) }}"

      - uses: softprops/action-gh-release@v2
        with:
          files: upper/bin/*
          tag_name: ${{ github.ref_name }} # default is github.ref, actually it's ref_name IIRC in source code
          # prerelease: true # FYI
          body: "experimental extra release demos?... changes"
          # FYI handling of release target commit if (or if not) `target_commitish` is set: https://github.com/softprops/action-gh-release/blob/810bfa2cd5f7c2bd4138fa75005d437ba562db81/src/github.ts#L229-L240
          #    if not set, then release keeps its original target_commitish
          target_commitish: ${{ github.sha }}
          # make_latest: true # defaults based on gh api
        # if: startsWith(github.ref, 'refs/tags/')
        # FYI if release is for new tag, it will use default branch if you don't specify a `target_commitish`...
        #
