name: upper image build

on:
  push:
    paths:
      - ".github/workflows/upper-image.yml"
      - "upper/**"
  workflow_dispatch: # manual

permissions:
  packages: write
  contents: read

jobs:
  image:
    # if: startsWith(github.ref, 'refs/tags/')
    name: image-pkg
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker version
      - run: docker image build -t upper-test .
        working-directory: ./upper
      - name: test it
        run: docker container run upper-test foo the bar
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }} # g0t4
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker tag upper-test ghcr.io/g0t4/upper-test:latest
      - run: docker tag upper-test ghcr.io/g0t4/upper-test:${{ github.ref_name }}
      - run: docker push ghcr.io/g0t4/upper-test:latest
      - run: docker push ghcr.io/g0t4/upper-test:${{ github.ref_name }}
